config/routes.rb
Rails.application.routes.draw do
  resources :employees
  resources :calendars do
    get :preferences
    post :preferences
    post :generate
  end
  devise_for :users
  resources :shifts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'home/index'

  root 'home#index'
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :calendar
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }
  validates_uniqueness_of :email, :scope => [:calendar_id]
  store_accessor :weekly_preferences, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday

  def set_preferences(preferred_shifts)
    preferred_shifts.each do |k, v|
      k.downcase

      if k.include? "mon"
        self.weekly_preferences[:monday].push(v)
      elsif k.include? "tues"
        self.weekly_preferences[:tuesday].push(v)
      elsif k.include? "wed"
        self.weekly_preferences[:wednesday].push(v)
      elsif k.include? "thurs"
        self.weekly_preferences[:thursday].push(v)
      elsif k.include? "fri"
        self.weekly_preferences[:friday].push(v)
      elsif k.include? "sat"
        self.weekly_preferences[:saturday].push(v)
      elsif k.include? "sun"
        self.weekly_preferences[:sunday].push(v)
      else
        #What to do if preferred shifts has none of these
      end
    end

    self.save
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :load_parent, only: [:create, :new, :index]
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  load_and_authorize_resource
  # GET /employees
  # GET /employees.json
  def index
    @employees = @parent.employees.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = @parent.employees.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = @parent.employees.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    calendar_id = @employee.calendar.id
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url(calendar_id: calendar_id), notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def load_parent
      @parent = Calendar.find(params[:calendar_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :email, :employee_num, :calendar_id, :user_id)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= hidden_field_tag :calendar_id, params[:calendar_id] %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :employee_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :employee_email %>
  </div>

  <div class="field">
    <%= form.label :employee_num %>
    <%= form.number_field :employee_num, id: :employee_employee_num %>
  </div>

  <div class="actions">
    <%= form.submit  %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee, :class => "btn btn-outline-secondary"  %> |
<%= link_to 'Back', employees_path(calendar_id: @employee.calendar.id), :class => "btn btn-outline-secondary"  %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<div class="btn-group">
  <%= link_to 'New Employee', new_employee_path(calendar_id: @parent.id), :class => "btn btn-primary" %>
  <%= link_to 'Back to Calendar', calendar_path(@parent), :class => "btn btn-outline-secondary" %>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <div class="row">
      <div class="col-xs-2">Employee Num</div>
      <div class="col-xs-2">Name</div>
      <div class="col-xs-2">Email</div>
      <div class="col-xs-6"></div>
    </div>
  </div>
  <div class="panel-body">
    <% @employees.each do |employee| %>
      <div class="row">
        <div class="col-xs-2"><%= employee.employee_num %></div>
        <div class="col-xs-2"><%= employee.name %></div>
        <div class="col-xs-2"><%= employee.email %></div>
        <div class="col-xs-2"><%= link_to 'Show', employee %></div>
        <div class="col-xs-2"><%= link_to 'Edit', edit_employee_path(employee) %></div>
        <div class="col-xs-2"><%= link_to 'Delete', employee, method: :delete, data: { confirm: 'Are you sure?' } %></div>
      </div>
    <% end %>
  </div>
</div>

<br>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee, :class => "btn btn-outline-secondary"  %>

<%= link_to 'Back', employees_path(calendar_id: @parent.id), :class => "btn btn-outline-secondary"  %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Employee Num:</strong>
  <%= @employee.employee_num %>
</p>


<%= link_to 'Edit', edit_employee_path(@employee), :class => "btn btn-outline-secondary"  %> |
<%= link_to 'Back', employees_path(calendar_id: @employee.calendar.id, :class => "btn btn-outline-secondary" ) %>