config/routes.rb
Rails.application.routes.draw do
  resources :employees
  resources :calendars do
    get :preferences
    post :preferences
    post :generate
  end
  devise_for :users
  resources :shifts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'home/index'

  root 'home#index'
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  belongs_to :user
  has_many :shifts, dependent: :destroy
  has_many :employees, dependent: :destroy

  def set_employee_preferences(params)
    # Parameters: { "employee_num"=>"234", 
    # "name"=>"Daniel Shu", 
    # "email"=>"email@email.com", 
    # "num_shifts"=>"3", 
    # "shift_1_Wed"=>"0", 
    # "shift_2_Tues"=>"0", 
    # "shift_3_Tues"=>"0", 
    # "shift_3_Wed"=>"0", 
    # "shift_3_Thurs"=>"0", 
    # "shift_4_Fri"=>"0", 
    # "shift_4_Sat"=>"0", 
    # "commit"=>"Save ", 
    # "calendar_id"=>"1"}
    puts self.employees.count

    employee = self.employees.find_by(email: params[:email])
    if employee.nil?
      employee = Employee.new(name: params[:name], email: params[:email])
      self.employees << employee
    else
      employee.name = params[:name]
    end
    employee.save

    preferred_shifts = params.select {|k,v| k.include? "shift@"}
    employee.set_preferences(preferred_shifts)
  end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :set_calendar, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource


  # GET /calendars
  # GET /calendars.json
  def index
    @calendars = current_user.calendars
  end

  # GET /calendars/1
  # GET /calendars/1.json
  def show
  end

  # GET /calendars/new
  def new
    @calendar = Calendar.new
  end

  # GET /calendars/1/edit
  def edit
  end

  # POST /calendars
  # POST /calendars.json
  def create
    @calendar = current_user.calendars.new(calendar_params)

    respond_to do |format|
      if @calendar.save
        format.html { redirect_to @calendar, notice: 'Calendar was successfully created.' }
        format.json { render :show, status: :created, location: @calendar }
      else
        format.html { render :new }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calendars/1
  # PATCH/PUT /calendars/1.json
  def update
    respond_to do |format|
      if @calendar.update(calendar_params)
        format.html { redirect_to @calendar, notice: 'Calendar was successfully updated.' }
        format.json { render :show, status: :ok, location: @calendar }
      else
        format.html { render :edit }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calendars/1
  # DELETE /calendars/1.json
  def destroy
    @calendar.destroy
    respond_to do |format|
      format.html { redirect_to calendars_url, notice: 'Calendar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def preferences
    @calendar = current_user.calendars.find(params[:calendar_id])
    @shifts = @calendar.shifts.all
    if request.post?
      @calendar.set_employee_preferences(params)
      redirect_to @calendar
    else

    end
  end

  def generate
    @calendar = current_user.calendars.find(params[:calendar_id])

    redirect_to @calendar
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calendar
      @calendar = current_user.calendars.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calendar_params
      params.require(:calendar).permit(:name)
    end
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/calendars/_form.html.erb
<%= form_with(model: calendar, local: true) do |form| %>
  <% if calendar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(calendar.errors.count, "error") %> prohibited this calendar from being saved:</h2>

      <ul>
      <% calendar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :calendar_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/calendars/edit.html.erb
<h1>Editing Calendar</h1>

<%= render 'form', calendar: @calendar %>

<%= link_to 'Show', @calendar, :class => "btn btn-outline-secondary"  %> |
<%= link_to 'Back', calendars_path, :class => "btn btn-outline-secondary"  %>

app/views/calendars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Calendars</h1>
<div class="btn-group">
  <%= link_to 'New Calendar', new_calendar_path, :class => "btn btn-primary" %> 
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <div class="row">
      <div class="col-md-4">Name</div>
      <div class="col-md-3"></div>
      <div class="col-md-3"></div>
      <div class="col-md-1"></div>
      <div class="col-md-1"></div>
    </div>
  </div>
  <div class="panel-body">
    <% @calendars.each do |calendar| %>
      <div class="row">
        <div class="col-md-4"><%= calendar.name %></div>
        <div class="col-md-3"><%= link_to 'Show Calendar', calendar %></div>
        <div class="col-md-3"><%= link_to 'View Employees', employees_path(calendar_id: calendar.id) %></div>
        <div class="col-md-1"><%= link_to 'Rename', edit_calendar_path(calendar) %></div>
        <div class="col-md-1"><%= link_to 'Delete', calendar, method: :delete, data: { confirm: 'Are you sure?' } %></div>
      </div>
    <% end %>
  </div>
</div>

<br>

app/views/calendars/new.html.erb
<h1>New Calendar</h1>

<%= render 'form', calendar: @calendar %>

<%= link_to 'Back', calendars_path %>

app/views/calendars/preferences.html.erb
<script>

  $(document).ready(function() {

    // page is now ready, initialize the calendar...

    $('#calendar').fullCalendar({
      // put your options and callbacks here
      header: {
                left: 'today',
                center: 'title',
                right: 'agendaWeek prev,next '
            },
      defaultView: "agendaWeek",
      events: "/shifts.json?calendar_id=<%=@calendar.id%>",
      timeFormat: 'h:mm a',
      height: "auto",
      eventClick: function(event) {
              if (event.url) {
                  return false;
              }
          },
    });

  });

</script>
<div class="row">
  <h1>Select Your Shift Preferences</h1>
</div>

<div class="col-lg-4">
  <%= link_to 'Back to Calendar', calendar_path(@calendar), :class => "btn btn-primary" %>

  <%= form_with url: calendar_preferences_path, method: "post" do |form| %>

    <div class="field">
      <%= form.label "Employee Num" %>
      <%= form.number_field :employee_num, id: :employee_employee_num %>
    </div>

    <div class="field">
      <%= form.label "Full Name" %>
      <%= form.text_field :name, id: :employee_name %>
    </div>

    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email, id: :employee_email %>
    </div>

    <div class="field">
      <%= form.label "Preferred Number of Shifts" %>
      <%= form.number_field :num_shifts, id: :employee_num_shifts %>
    </div>

    <h3>Shifts</h3>
    <p>Please select all shifts you are willing to work.</p>
    <p>Note: For overnight or multi-day shifts, the day of the week listed is the day that the shift STARTS on.</p>
    <div class="container">
      <% @shifts.each do |shift| %>
        <h4><%= shift.title %> <%= Shift.format_time_ampm(shift.start_time) %> - <%= Shift.format_time_ampm(shift.end_time) %></h4>
        <div class="checkboxes">
          <ul>
            <% (0..6).each do |i|%>
              <% if shift.weekdays.include?(i) %>
                <li><%= check_box_tag "shift_#{shift.id}_#{weekdays_int_to_string[i]}", shift.id %> <%= weekdays_int_to_string[i] %> </li>
              <% end %>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

</div>

<div class="col-lg-8">
  <div id="calendar" />
</div>

app/views/calendars/show.html.erb
<script>

  $(document).ready(function() {

    // page is now ready, initialize the calendar...

    $('#calendar').fullCalendar({
      // put your options and callbacks here
      header: {
                left: 'today',
                center: 'title',
                right: 'agendaWeek,agendaDay prev,next '
            },
      defaultView: "agendaWeek",
      events: "/shifts.json?calendar_id=<%=@calendar.id%>",
      timeFormat: 'h:mm a',
      height: "auto",
    });

  });

</script>

<p id="notice"><%= notice %></p>

<h1><%= @calendar.name %> Shifts</h1>

<div class="btn group">
  <%= link_to 'New Shift', new_shift_path(calendar_id: @calendar.id), :class => "btn btn-primary" %> 
  <%= link_to 'Preference Form', calendar_preferences_path(@calendar), :class => "btn btn-primary" %> 
  <%= link_to 'Employees', employees_path(calendar_id: @calendar.id), :class => "btn btn-outline-secondary" %> |
  <%= link_to 'Change Calendar Name', edit_calendar_path(@calendar), :class => "btn btn-outline-secondary" %> |
  <%= link_to 'Back', calendars_path, :class => "btn btn-outline-secondary" %>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <div class="row">
      <div class="col-xs-3">Title</div>
      <div class="col-xs-4">Days of Week</div>
      <div class="col-xs-1">Start Time</div>
      <div class="col-xs-1">End Time</div>
      <div class="col-xs-3"></div>
    </div>
  </div>
  <div class="panel-body">
    <% @calendar.shifts.each do |shift| %>
      <div class="row">
        <div class="col-xs-3"><%= shift.title %></div>
        <div class="col-xs-4"><%= shift.get_weekdays_as_string %></div>
        <div class="col-xs-1"><%= Shift.format_time_ampm(shift.start_time) %></div>
        <div class="col-xs-1"><%= Shift.format_time_ampm(shift.end_time) %></div>
        <div class="col-xs-1"><%= link_to 'Show', shift %></div>
        <div class="col-xs-1"><%= link_to 'Edit', edit_shift_path(shift) %></div>
        <div class="col-xs-1"><%= link_to 'Delete', shift, method: :delete, data: { confirm: 'Are you sure?' } %></div>
      </div>
    <% end %>
  </div>
</div>

<div>
  <p> Generate a schedule using all shifts and submitted employee preferences: </p>
  <%= link_to 'Generate Schedule', calendar_generate_path(@calendar), method: :post, :class => "btn btn-lg btn-success" %> 
</div>


<br>

<br>

<div id="calendar"></div>